# Default values for red-delivery.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: '1'
resources:
  requests:
    memory: 1Gi
    cpu: 10m
  limits:
    memory: 1Gi
    cpu: "1"
url:
  - ""
image: ghcr.io/spring-media/github-demo/universe-2020-demo:c9f53b7
