{{- $chartname := .Release.Name -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.effectiveNamespace | default .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: skipper
spec:
  rules:
{{- range $index, $val := .Values.url }}
    - host: {{ $val }}
      http:
        paths:
          - backend:
              serviceName: {{ $chartname }}-service
              servicePort: 80
{{- end }}
