apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-pre-install"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: "{{.Release.Name}}-pre-install"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install-job
        image: "ghcr.io/spring-media/github-api-client:latest"
        command: ["/scripts/switchDeploymentState.sh"]
        env:
          - name: IMAGE
            value: {{ .Values.image | quote }}
          - name: PROJECT
            value: {{ .Chart.Name | quote }}
          - name: CURRENT_STATE
            value: "success"
          - name: DESIRED_STATE
            value: "inactive"
          - name: GITHUB_API_USER
            valueFrom:
              secretKeyRef:
                name: github-api-secret
                key: username
          - name: GITHUB_API_PASSWD
            valueFrom:
              secretKeyRef:
                name: github-api-secret
                key: password

      imagePullSecrets:
        - name: github-pull-secret
