name: Docker

on:
  push:
    branches-ignore:
      - main

env:
  IMAGE_NAME: universe-2020-demo

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.DFASSBENDER_GITHUB_TOKEN }}" | docker login ghcr.io -u dfassbender --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=${GITHUB_SHA::7}
          LABEL=$(echo ${{github.event.ref}} | sed 's/refs\/heads\///g' | tr '[:upper:]' '[:lower:]' | awk -F "-" '{print $1 "-" $2 "-" $3}')

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          echo LABEL=$LABEL

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$LABEL-$VERSION
