name: Delete Phoenix

on:
  delete:
    branches-ignore:
      - master

jobs:
  delete_phoenix:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Phoenix
        run: |
          PROJECT="github-demo"
          LABEL=$(echo ${{github.event.ref}} | sed 's/refs\/heads\///g' | tr '[:upper:]' '[:lower:]' | awk -F "-" '{print $1 "-" $2 "-" $3}')

          PAYLOAD="{\"ref\":\"main\",\"inputs\":{\"phoenixName\":\"$LABEL\",\"projectName\":\"$PROJECT\"}}"
          echo $(echo $PAYLOAD)
          curl -X POST -d "$PAYLOAD" -H "authorization: Bearer ${{ secrets.DEMO_GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/spring-media/github-demo-flux-cd/actions/workflows/destroy-phoenix.yaml/dispatches

      - name: Remove deployment
        run: |
          # remove all deployments of this phoenix environment
          LABEL=$(echo ${{github.event.ref}} | sed 's/refs\/heads\///g' | tr '[:upper:]' '[:lower:]' | awk -F "-" '{print $1 "-" $2 "-" $3}')
          DEPLOYMENT_IDS=$(curl -s -X GET -H "authorization: Bearer ${{ secrets.DEMO_GITHUB_TOKEN }}" -H "Accept:application/vnd.github.ant-man-preview+json" https://api.github.com/repos/spring-media/github-demo/deployments | jq ".[] | select(.environment == \"${LABEL}.test\")" | jq '.id')

          PAYLOAD="{\"state\": \"inactive\",\"description\": \"Deployment status switched to inactive.\"}"
          
          for DEPLOYMENT_ID in $DEPLOYMENT_IDS
          do
          	curl -s -X POST -d "${PAYLOAD}" -H "authorization: Bearer ${{ secrets.DEMO_GITHUB_TOKEN }}" -H "Accept:application/vnd.github.ant-man-preview+json" https://api.github.com/repos/spring-media/github-demo/deployments/"${DEPLOYMENT_ID}"/statuses
            curl -s -X DELETE -H "authorization: Bearer ${{ secrets.DEMO_GITHUB_TOKEN }}" -H "Accept:application/vnd.github.ant-man-preview+json" https://api.github.com/repos/spring-media/github-demo/deployments/"${DEPLOYMENT_ID}"
          done
